-- -- Active: 1703925228325@@127.0.0.1@3306@book_shop
SELECT birthdate FROM people;
SELECT CURDATE();
SELECT birthdate, DATEDIFF(CURDATE(), birthdate) FROM people;
SELECT DATE_ADD(CURDATE(), INTERVAL 1 YEAR);
SELECT DATE_ADD(CURDATE(), INTERVAL 1 MONTH);
SELECT DATE_SUB(CURDATE(), INTERVAL 1 YEAR);
SELECT birthdate, DATE_ADD(birthdate, INTERVAL 18 YEAR) FROM people;

SELECT CURTIME();
SELECT TIMEDIFF(CURTIME(), '07:00:00');
SELECT 2-2;
SELECT NOW() - INTERVAL 18 YEAR;

SELECT name, birthdate , birthdate + INTERVAL 21 year FROM people;